#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only

# ./genconfig.sh - generate C header for setting the correct preprocessor definitions for the kernel version
# Usage ./genconfig.sh <kernel version> <make flags>
# The make flags are used for determining concurrency for the feature tests, it pulls out the value of the -j flag.
# ./genconfig.sh `uname -r` "-j4", four threads for running feature tests
# ./genconfig.sh `uname -r` "-i -j4 -d", doesn't care about other flags present

TEXT_COLOR='\033[0;31m' #Red
BG_COLOR='\033[43m' # Yellow background
NC='\033[0m' # No Color

function echo_highlight() {
    echo -e "${TEXT_COLOR}${BG_COLOR}$1${NC}"
}

SRC_DIR=$(dirname "$0")
OUTPUT_FILE=$SRC_DIR/kernel-config.h
FEATURE_TEST_DIR="$SRC_DIR/configure-tests/feature-tests"
FEATURE_TEST_FILES="$FEATURE_TEST_DIR/*.c"
SYMBOL_TESTS_FILE="$SRC_DIR/configure-tests/symbol-tests"
KERNEL_VERSION=$(uname -r)
MAX_THREADS=$(echo "$2" | sed -E 's/.*-j\s*([0-9]+).*/\1/')
if ! [[ "$MAX_THREADS" =~ '^[0-9]+$' ]]; then # if there was no -j flag provided, default to the number of processors
	MAX_THREADS=$(getconf _NPROCESSORS_ONLN)
fi

if [ ! -z "$1" ]; then
	KERNEL_VERSION="$1"
fi

SYSTEM_MAP_FILE="/lib/modules/${KERNEL_VERSION}/System.map"

# Use standard location at the /boot
[ ! -f "$SYSTEM_MAP_FILE" ] && SYSTEM_MAP_FILE="/boot/System.map-${KERNEL_VERSION}"
if [ ! -f "$SYSTEM_MAP_FILE" ] || [ $(cat "$SYSTEM_MAP_FILE" | wc -l) -lt 10 ]; then
	# The build is running on Debian 11+. File /boot/System.map-${KERNEL_VERSION} exists, but it
	# contains just a single line.
	# Maybe package linux-image-$(uname -r)-dbg is installed...
	SYSTEM_MAP_FILE="/usr/lib/debug/boot/System.map-${KERNEL_VERSION}"

	if [ ! -f "$SYSTEM_MAP_FILE" ]
	then
		# Detect if runing kernel version and `uname -r` are different, which meaning an upgrade is on-going
		RUNNING_KERNEL_VERSEION="$(cat /proc/version | sed 's|^Linux\ version\ \([^ ]\+\)\ .*|\1|g')"
		if [ "${RUNNING_KERNEL_VERSEION}" != "${KERNEL_VERSION}" ]
		then
			# No valid SystemMap found and /proc/kallsyms not usable becuase it's upgrade, so we make build fail
			echo_highlight "* System map at /boot/System.map-${KERNEL_VERSION} does not contain valid symbol table, and "
			echo_highlight "* we are trying to install synosnap driver for a differnt kernel than the one currently running."
			echo_highlight "* Synosnap driver will encounter error during installation."
			echo_highlight "* We will try to install/build driver when next booting into new kernel."
			echo_highlight "* After rebooting into the new kernel, if the backup process still fails,"
			echo_highlight "* please uninstall and reinstall Active Backup for Business Linux Agent."

			exit 1
		fi
	fi

	# For non-upgrading case, we can use /proc/kallsyms for target kernel systemmap because it's the samw as current one
	# Use fallback option
	[ ! -f "$SYSTEM_MAP_FILE" ] && SYSTEM_MAP_FILE="/proc/kallsyms"
fi


echo "generating configurations for kernel-${KERNEL_VERSION}"

rm -f $OUTPUT_FILE

echo "//The values in this file should be generated by the build process. Do not alter." >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "#ifndef DATTOBD_KERNEL_CONFIG_H" >> $OUTPUT_FILE
echo "#define DATTOBD_KERNEL_CONFIG_H" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

make -s -C $FEATURE_TEST_DIR clean KERNELVERSION=$KERNEL_VERSION

# Resolve absolute path to main source dir for -I include path
REAL_SRC_DIR="$(cd "$SRC_DIR" && pwd -P)"

run_one_test() {
	local SRC_FILE="$1"
	local TEST="$(basename $SRC_FILE .c)"
	local OBJ="$TEST.o"
	local MACRO_NAME="HAVE_$(echo ${TEST} | awk '{print toupper($0)}')"
	local PREFIX="performing configure test: $MACRO_NAME -"

	# Build each test in its own temp directory to avoid parallel build races.
	# Kernel 6.12+ kbuild no longer resolves source via src= parameter, and
	# parallel builds in the same M= directory collide on auxiliary files.
	local TMPDIR=$(mktemp -d)
	ln -s "$(readlink -f "$SRC_FILE")" "$TMPDIR/$TEST.c"

	# Create a per-test Kbuild file (use ccflags-y, not EXTRA_CFLAGS — removed in 6.17)
	printf 'obj-m := %s\nccflags-y := -g -Werror -I%s\n' \
		"$OBJ" "$REAL_SRC_DIR" > "$TMPDIR/Kbuild"

	if make -C /lib/modules/$KERNEL_VERSION/build M="$TMPDIR" modules &>/dev/null ; then
		echo "$PREFIX present"
		echo "#define $MACRO_NAME" >> $OUTPUT_FILE
	else
		echo "$PREFIX not present"
	fi
	rm -rf "$TMPDIR"
}
export -f run_one_test
export FEATURE_TEST_DIR
export KERNEL_VERSION
export OUTPUT_FILE
export REAL_SRC_DIR

ls -1 -q $FEATURE_TEST_FILES | xargs -P "$MAX_THREADS" -d"\n" -I {} bash -c 'run_one_test {}'

make -s -C $FEATURE_TEST_DIR clean KERNELVERSION=$KERNEL_VERSION

while read SYMBOL_NAME; do
	if [ -z "$SYMBOL_NAME" ]; then
		continue
	fi

	echo "performing $SYMBOL_NAME lookup"
	MACRO_NAME="$(echo ${SYMBOL_NAME} | awk '{print toupper($0)}')_ADDR"
	SYMBOL_ADDR=$(grep " ${SYMBOL_NAME}$" "${SYSTEM_MAP_FILE}" | awk '{print $1}')
	if [ -z "$SYMBOL_ADDR" ]; then
		SYMBOL_ADDR="0"
	fi
	echo "#define $MACRO_NAME 0x$SYMBOL_ADDR" >> $OUTPUT_FILE
done < $SYMBOL_TESTS_FILE

if mount -V 2>&1 | grep -q "fd-based-mount"; then
	echo "#define USE_NEW_MOUNT_API" >> $OUTPUT_FILE
fi

echo "" >> $OUTPUT_FILE
echo "#endif" >> $OUTPUT_FILE
